apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-acos-instance-gateway
  name: fint-flyt-acos-instance-gateway
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-acos-instance-gateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fint-flyt-acos-instance-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "viken-no-skjema.vigoiks.no"
      http:
        paths:
          - path: /api/instans/acos
            pathType: Prefix
            backend:
              service:
                name: fint-flyt-acos-instance-gateway
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-acos-instance-gateway
  name: fint-flyt-acos-instance-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-acos-instance-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-acos-instance-gateway
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-acos-instance-gateway:dummy
          name: fint-flyt-acos-instance-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc' }
            - { name: fint.org-id, value: 'viken.no' }
            - { name: fint.flyt.resource-server.security.api.external.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.external.authorized-client-ids, value: '1' }