apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-acos-instance-gateway_bfk_no
  fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kbfka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/bfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/bfk-no/api/acos/instances"

    target:
      kind: Application
      name: fint-flyt-acos-instance-gateway

