apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-acos-instance-gateway_afk_no
      fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/afk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/afk-no/api/acos/instances"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/afk-no/actuator/health"

    target:
      kind: Application
      name: fint-flyt-acos-instance-gateway

